FROM golang:1.20-alpine

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/egress ./egress/cmd/...

EXPOSE 8000/tcp

CMD ["egress"]
